import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`
    "coverage/**",
    // Browser extension: plain JS for Chrome, not part of the Next app
    "extension/**",
    // Desktop tray app: plain CommonJS for Electron, with its own package.json
    "desktop/**",
    // Generated copy of the code editor (scripts/copy-monaco.mjs)
    "public/monaco/**",
  ]),
  // The database client is used in src/lib/db only; everything else calls a function from there,
  // so every query and its ownership check live in one layer.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/db/**", "src/lib/prisma.ts", "src/**/*.test.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/lib/prisma", "**/lib/prisma", "./prisma"],
              message: "Add a function to src/lib/db instead of using the Prisma client directly.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
