import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`
    "coverage/**",
    // Browser extension: plain JS for Chrome, not part of the Next app
    "extension/**",
    // Desktop tray app: plain CommonJS for Electron, with its own package.json
    "desktop/**",
  ]),
]);

export default eslintConfig;
