import type { Metadata } from "next";
import { LegalPage } from "@/components/shared/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The rules for using BitBin, including the Free and Pro plans.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="6 October 2026">
      <p>
        By creating an account or using BitBin you agree to these terms. BitBin is a portfolio project run by one
        person, offered as is; please read the sections on availability and liability.
      </p>

      <h2>Your account</h2>
      <p>
        You are responsible for what happens under your account, so keep your password safe. Give a real email address
        you can read, and do not create accounts to get around limits or to disrupt the service. You must be at least
        16.
      </p>

      <h2>Your content</h2>
      <p>
        You own what you save. You give BitBin permission to store, process and display it to you, and to send it to
        the AI provider when you ask for an AI feature, solely to run the service. Do not save anything illegal, do not
        upload malware, and do not store content you have no right to keep. Items are private to you; there is no
        sharing feature.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>No attacking, probing or overloading the service, and no attempts to reach other people&apos;s data.</li>
        <li>No automated bulk use outside the documented token API, and no bypassing rate limits or plan limits.</li>
        <li>The demo account is a shared sandbox; do not use it for anything private or abusive.</li>
      </ul>
      <p>Accounts that break these rules may be limited or removed.</p>

      <h2>Plans and billing</h2>
      <ul>
        <li>
          <strong>Free</strong> has limits on items and collections. <strong>Pro</strong> adds files, images, AI
          features, the token API and ZIP export.
        </li>
        <li>
          Pro is a subscription billed by Stripe monthly or yearly and renews until you cancel. Cancel any time in the
          billing portal; Pro stays active until the end of the paid period.
        </li>
        <li>Prices may change for future periods, with notice before your next renewal.</li>
        <li>Refunds are considered case by case; open an issue on the project repository.</li>
      </ul>

      <h2>AI features</h2>
      <p>
        Suggestions are generated by a model and can be wrong. Check them before relying on them, especially generated
        code.
      </p>

      <h2>Availability and changes</h2>
      <p>
        The service is provided &quot;as is&quot;, with no promise that it will always be available or free of errors.
        Features may change or be removed. Keep your own copy of anything important; Pro accounts can export a ZIP.
      </p>

      <h2>Ending your account</h2>
      <p>
        You can delete your account in Settings at any time, which removes your data as described in the{" "}
        <a href="/privacy">Privacy Policy</a>. We may suspend or end accounts that break these terms.
      </p>

      <h2>Liability</h2>
      <p>
        To the extent the law allows, BitBin and its author are not liable for lost data, lost profits or indirect
        damages arising from use of the service. Nothing here limits rights you have under law that cannot be waived.
      </p>

      <h2>Contact</h2>
      <p>
        Questions or problems: open an issue on the{" "}
        <a href="https://github.com/Divyanshu2805/bitbin/issues">project repository</a>.
      </p>
    </LegalPage>
  );
}
